### ISSUE TITLE
World Startup Console Issue

### ISSUE THREAD

**Issue by Darkosto** [GoryMoon/HorsePower#20] opened 2017-11-03 06:16 UTC
Heya Gory,

I was testing out the pack tonight and came across this issue during world load:
https://gist.github.com/Darkosto/d5a584ea073734f0bb8a38d19319087e

Could you please take a look when you have a moment? Thank you :)

**Comment by Darkhax** [comment] 2017-11-03 06:21
To provide additional context, you're removing recipes from JEI on the wrong thread. Normally this will not crash the game but will generate obscure issues such as [this](https://pastebin.com/p4qgCktE) one. The crash shown in Darkosto's issue was caused by a special build of JEI that mezz made for tracking these sorts of things. I've attached a zip file which contains a jar that can be used to reproduce this issue. 

[jei_1.12.2-4.8.0=exploding-version-do-not-use-in-production-seriously.zip](https://github.com/GoryMoon/HorsePower/files/1440200/jei_1.12.2-4.8.0.exploding-version-do-not-use-in-production-seriously.zip)

**Comment by GoryMoon** [comment] 2017-11-05 00:57
Fixed in the latest release 2.5.8.52. 
Ended up removing that part, with the changes to JEI it didn't really work that well as it now just hides the recipes then removing them. 
To get the recipes to show in JEI after changing the config you need to reload the resources F3+T now or restart the game.

**Closed as completed by GoryMoon** 2017-11-05 00:57 UTC
